id: AF56FD7E2
title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of the Vast
  Expanse
type: translation
pechas:
- I4B55717C
- IEACD06BA
- I341ADD7E
- I03BF70B8
- I6831F35F
- ICE8C298C
source_metadata:
  languages:
  - en
  - de
  - fr
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:40:25.013160
  last_modified_at: 2023-01-04 12:40:25.013201
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I4B55717C/43CD: 4FF8
  IEACD06BA/6C8E: 4FF8
  I341ADD7E/6953: 4FF8
  I03BF70B8/E460: 4FF8
  I6831F35F/484C: 4FF8
  ICE8C298C/2A36: 4FF8
